name: Build all

on:
  workflow_dispatch:
    inputs:
      build-deps-only:
        description: 'Only build dependencies'
        type: boolean
        default: false
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux_arm64:
    name: Build Linux ARM64
    uses: ./.github/workflows/build_deps.yml
    with:
      os: 'ubuntu-latest'
      arch: 'aarch64'
      cache-path: 'deps/build'
      cache-key: 'elegoo-linux-arm64-v1'
      valid-cache: false
    secrets: inherit


