name: Build Dependencies Linux ARM64

on:
  workflow_call:
    inputs:
      cache-key: { required: true, type: string }
      cache-path: { required: true, type: string }
      os: { required: true, type: string }
      arch: { required: true, type: string }
      valid-cache: { required: false, type: boolean, default: false }

jobs:
  build_deps:
    name: Build Dependencies (Linux ARM64)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up QEMU for ARM64
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Load cached deps
        uses: actions/cache@v4
        with:
          path: ${{ inputs.cache-path }}
          key: ${{ inputs.cache-key }}
          fail-on-cache-miss: false

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libglew-dev m4 libdbus-1-dev binutils-aarch64-linux-gnu
          chmod +x ./BuildLinux.sh

      - name: Run Build Scripts
        if: inputs.valid-cache == false
        run: |
          # Install libs, build math deps, then build the app
          sudo ./BuildLinux.sh -u
          ./BuildLinux.sh -d
          ./BuildLinux.sh -i

      - name: Locate Built Files
        run: |
          echo "Searching for results..."
          find . -name "*.AppImage" -o -name "*.deb"

      - name: Upload Linux ARM64 Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ElegooSlicer-Linux-ARM64
          # The ** searches all subfolders to find the AppImage
          path: "**/*.AppImage"
          if-no-files-found: warn
          retention-days: 5

      - name: Force Save Cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ${{ inputs.cache-path }}
          key: ${{ inputs.cache-key }}
