name: Build Elegoo Slicer Linux
on: [workflow_dispatch] # Allows you to start the build manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          # This ensures maximum space for the 10GB+ build

      - name: Install Dependencies
        run: ./BuildLinux.sh -u

      - name: Build Dependencies
        run: ./BuildLinux.sh -d

      - name: Build Slicer
        run: ./BuildLinux.sh -s

      - name: Create AppImage
        run: ./BuildLinux.sh -i

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ElegooSlicer-Linux
          path: ./build/package/*.AppImage
